# Generated by Django 2.2.1 on 2020-07-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='photo.jpg', null=True, upload_to='bg_image'),
        ),
    ]
