# Generated by Django 2.2.1 on 2020-07-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_avatarphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
