# Generated by Django 2.2.1 on 2020-08-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
