# Generated by Django 2.2.1 on 2020-08-07 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_post_user_tagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_tagged',
        ),
        migrations.AddField(
            model_name='post',
            name='user_tagged',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_tagged', to=settings.AUTH_USER_MODEL),
        ),
    ]
