# Generated by Django 2.2.1 on 2020-08-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200808_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='place',
            new_name='country',
        ),
    ]
