# Generated by Django 2.2.1 on 2020-08-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200823_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job',
            new_name='profession',
        ),
    ]
